version: '2'
services: 
    mysql:
        image: mariadb:10.5
        volumes: 
            - vlb-mysqldb:/var/lib/mysql
            - ./cmdi_forms.sql:/docker-entrypoint-initdb.d/cmdi_forms.sql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWD:-rood}
            MYSQL_DATABASE: "cmdi_forms"
        networks:
            - ccf 

    # huc-editor backend & frontend
    php-apache:
        build:
            context: .
            dockerfile: Dockerfile
#        ports:
#            - 80:80
        volumes: 
#            - ./html:/var/www/html/ # during development       
            - vlb-records:/var/www/html/ccf/data/records/inprogress      
        environment:
            TITLE: "HuC generic Editor"
            PROFILE: "Vragenlijst"
            SUBTITLE: "All you need for development"
            BASE_URL: "http://localhost/ccf/"
            TZ: "Europe/Amsterdam"
            DB_SERVER: mysql
            DB_USER: root
            DB_PASSWD: ${DB_PASSWD:-rood}
            DB_NAME: cmdi_forms
            VIRTUAL_HOST: "vlb.sd.di.huc.knaw.nl"
        networks:
            - ccf
        depends_on:
            - mysql
networks:
    ccf:
        external: false
volumes:
    vlb-mysqldb: 
    vlb-records:      