version: '3'
services: 
    mysql:
        image: mariadb:10.5
        volumes: 
            - mysqldb:/var/lib/mysql
            - ./cmdi_forms.sql:/docker-entrypoint-initdb.d/cmdi_forms.sql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWD:-rood}
            MYSQL_DATABASE: "cmdi_forms"
        networks:
            - ccf 

    # huc-editor backend & frontend
    php-apache:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
        volumes: 
            - ./html:/var/www/html/ # during development       
        environment:
            TITLE: "Vocabulary Editor"
            PROFILE: "Vocabulary"
            SUBTITLE: "Maintain vocabs"
            BASE_URL: "http://localhost/ccf/"
            TZ: "Europe/Amsterdam"
            DB_SERVER: mysql
            DB_USER: root
            DB_PASSWD: ${DB_PASSWD:-rood}
            DB_NAME: cmdi_forms
        networks:
            - ccf
        depends_on:
            - mysql
networks:
    ccf:
        external: false
volumes:
    mysqldb:       
    cmdirecords: