version: '3'
services: 
    mysql:
        image: mariadb:10.5
        volumes: 
            - mysqldb:/var/lib/mysql
            - ./mysql/cmdi_forms.sql:/docker-entrypoint-initdb.d/cmdi_forms.sql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWD:-rood}
            MYSQL_DATABASE: "cmdi_forms"
        networks:
            - ccf 

    # huc-editor backend & frontend
    php-apache:
        build:
            context: .
            dockerfile: Dockerfile.serve
        ports:
            - 80:80
        volumes: 
            - ccf-html:/tmp/html
        environment:
            TITLE: "HuC generic Editor"
            PROFILE: "Interview"
            SUBTITLE: "All you need for development"
            BASE_URL: "http://localhost/ccf/"
            TZ: "Europe/Amsterdam"
            DB_SERVER: mysql
            DB_USER: root
            DB_PASSWD: ${DB_PASSWD:-rood}
            DB_NAME: cmdi_forms
        networks:
            - ccf
        depends_on:
            - mysql
            - editor
            - parser
            - app

    # CMDI editor
    editor:
        image: ghcr.io/knaw-huc/huc-generic-editor:latest
        volumes:
            - ccf-html:/tmp/html
        entrypoint: ["cp", "-r", "/usr/share/nginx/html/css", "/usr/share/nginx/html/js", "/tmp/html/ccf/"]
        depends_on:
            - app
    # CMDI parser
    parser:
        image: ghcr.io/knaw-huc/clariah-cmdi-parser:latest
        volumes:
            - ccf-html:/tmp/html
        entrypoint: ["cp", "-r", "/var/www/html/classes", "/var/www/html/tweaker", "/tmp/html/ccf/"]
        depends_on:
            - app
    # CMDI app
    app:
        image: huccmdiapp:latest
        volumes:
            - ccf-html:/tmp/html
        entrypoint: ["cp", "-r", "/var/www/html", "/tmp/"]

networks:
    ccf:
        external: false
volumes:
    mysqldb:       
    cmdirecords:
    ccf-html: