version: '2'
services: 
    nde-mysql:
        build:
            context: .
            dockerfile: ./Dockerfile.mariadb
        volumes: 
            - nde-mysqldb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWD:-rood}
            MYSQL_DATABASE: "cmdi_forms"
        networks:
            - nde-network 

    # huc-editor backend & frontend
    nde-php-apache:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8124:80
        volumes:
            - ./data/records/:/var/www/html/ccf/data/records/
            - ./data/resources/:/var/www/html/ccf/data/resources/
        environment:
            TITLE: "NDE DCat Editor"
            PROFILE: "DCat"
            SUBTITLE: "your way to INEO"
            BASE_URL: "https://nde.sd.di.huc.knaw.nl/ccf/"
#            BASE_URL: "http://0.0.0.0:8124/ccf/"
            TZ: "Europe/Amsterdam"
            DB_SERVER: nde-mysql
            DB_USER: root
            DB_PASSWD: ${DB_PASSWD:-rood}
            DB_NAME: cmdi_forms
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nde.entrypoints=http"
        - "traefik.http.routers.nde.rule=Host(`nde.sd.di.huc.knaw.nl`)"
        networks:
            - nde-network
        depends_on:
            - nde-mysql
networks:
  nde-network:
#    external: false
    external:
      name: traefik-public
volumes:
    nde-mysqldb:
