version: '3'
services: 
    mysql:
        image: mariadb:10.5
        volumes: 
            - mysqldb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: rood
            MYSQL_DATABASE: "cmdi_forms"

    # huc-editor backend & frontend
    php-apache:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
        volumes: 
            - ./html:/var/www/html/
        environment:
            TITLE: "Oral history editor "
            PROFILE: "Interview"
            PROFILE_ID: "p_163300033799"
            SUBTITLE: "All you need for development and light entertainment "
            THUIS: "http://localhost/ccf/"
            TZ: "Europe/Amsterdam"
            DB_SERVER: mysql
            DB_USER: root
            DB_PASSWD: rood
            DB_NAME: cmdi_forms


volumes:
    mysqldb:       