version: '2'
services: 
    mysql:
        build:
            context: .
            dockerfile: ./Dockerfile.mariadb
        volumes: 
            - vlb-mysqldb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWD:-rood}
            MYSQL_DATABASE: "cmdi_forms"
        networks:
            - ccf 

    # huc-editor backend & frontend
    php-apache:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8123:80
        volumes: 
#            - ./html:/var/www/html/ # during development       
            - vlb-records:/var/www/html/ccf/data/records/inprogress      
        environment:
            TITLE: "HuC generic Editor"
            PROFILE: "Vragenlijst"
            SUBTITLE: "All you need for development"
            BASE_URL: "http://localhost/ccf/"
            TZ: "Europe/Amsterdam"
            DB_SERVER: mysql
            DB_USER: root
            DB_PASSWD: ${DB_PASSWD:-rood}
            DB_NAME: cmdi_forms
            VIRTUAL_HOST: "vlb.sd.di.huc.knaw.nl"
            VIRTUAL_PORT: 80
        networks:
            - ccf
        depends_on:
            - mysql
networks:
    ccf:
        external:
            name: nginxproxynetwork
volumes:
    vlb-mysqldb: 
    vlb-records:      